kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/toughIQ/ocp-build-demo.git'
  name: ocp-build-demo-git
  labels:
    app: ocp-build-demo-git
    app.kubernetes.io/component: ocp-build-demo-git
    app.kubernetes.io/instance: ocp-build-demo-git
    app.kubernetes.io/part-of: ocp-build-demo
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'docker.io/toughiq/ocp-build-demo-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/toughIQ/ocp-build-demo.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: ocp-build-demo-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: ocp-build-demo-git-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
